const testData = [
    {
        controlType: 'Input',
        coreDiseasePatId: '22021775970',
        deAttributeName: 'ti_count',
        deDisable: false,
        deHide: false,
        deId: 'MCDE-00399',
        deMemo: 'TI评分指标',
        deTitleHide: true,
        deType: 'int',
        deValue: '0',
        deValueText: 3,
        dsAttributeName: 'ti_info',
        ifQualityControl: false,
        ifReportNode: true,
        ifRequired: false,
        ifStandard: false,
        ifTimeNode: false,
        isDel: 0,
        multiple: false,
        scoreType: 1,
    },
    {
        controlType: 'Input',
        coreDiseasePatId: '22021775970',
        deAttributeName: 'gcs_count',
        deDisable: false,
        deHide: false,
        deId: 'MCDE-00394',
        deMemo: 'GCS昏迷指数分值',
        deTitleHide: true,
        deType: 'string',
        deValue: '0',
        deValueText: 0,
        dsAttributeName: 'gcs_info',
        ifQualityControl: false,
        ifReportNode: true,
        ifRequired: false,
        ifStandard: false,
        ifTimeNode: false,
        isDel: 0,
        multiple: false,
        scoreType: 1,
    },
    {
        controlType: 'Input',
        coreDiseasePatId: '22021775970',
        deAttributeName: 'iss_totle_scroce',
        deDisable: false,
        deHide: false,
        deId: 'MCDE-00348',
        deMemo: '总分',
        deTitleHide: false,
        deType: 'string',
        deValue: '0',
        deValueText: 0,
        dsAttributeName: 'iss_info',
        ifQualityControl: false,
        ifReportNode: true,
        ifRequired: false,
        ifStandard: false,
        ifTimeNode: false,
        isDel: 0,
        multiple: false,
        scoreType: 1,
    },
    {
        controlType: 'Input',
        deAttributeName: 'iss_max_scroce',
        deDisable: false,
        deHide: false,
        deId: 'MCDE-00349',
        deMemo: '最大分',
        deTitleHide: false,
        deType: 'string',
        dsAttributeName: 'iss_info',
        ifQualityControl: false,
        ifReportNode: true,
        ifRequired: false,
        ifStandard: false,
        ifTimeNode: false,
        isDel: 0,
        multiple: false,
        scoreType: 2,
        deValueText: 0,
    },
    {
        controlType: 'Input',
        deAttributeName: 'pre_hospital_transfer_cost',
        deDisable: false,
        deHide: false,
        deId: 'MCDE-00091',
        deMemo: '院前急救转运时间',
        deTitleHide: false,
        deType: 'string',
        dsAttributeName: 'inner_admission',
        ifQualityControl: false,
        ifReportNode: true,
        ifRequired: false,
        ifStandard: false,
        ifTimeNode: false,
        isDel: 0,
        multiple: false,
        regex: '/^[0-9]*$/',
        regexMissMatch: '请输入数字',
        deValueText: '',
    },
    {
        controlType: 'Options',
        cvItems: [
            { cvCode: 'MCCV-00020-001-001', cvDisabled: false, cvId: 'MCCV-00020', cvSelected: true, cvValue: '1', cvValueText: '是', fieldOrder: 1 },
            { cvCode: 'MCCV-00020-001-002', cvDisabled: false, cvId: 'MCCV-00020', cvSelected: false, cvValue: '2', cvValueText: '否', fieldOrder: 2 },
        ],
        deAttributeName: 'is_diagnose_conform',
        deCvId: 'MCCV-00020',
        deDisable: false,
        deHide: false,
        deId: 'MCDE-00095',
        deMemo: '是否符合',
        deTitleHide: false,
        deType: 'string',
        dsAttributeName: 'diagnose_condition',
        ifQualityControl: false,
        ifReportNode: true,
        ifRequired: false,
        ifStandard: false,
        ifTimeNode: false,
        isDel: 0,
        multiple: false,
        deValueText: '是',
    },
    {
        controlType: 'Input',
        coreDiseasePatId: '22021775970',
        deAttributeName: 'outcome_diagnose',
        deDisable: false,
        deHide: false,
        deId: 'MCDE-00094',
        deMemo: '出院诊断',
        deTitleHide: false,
        deType: 'string',
        deValue: '角膜伤口漏',
        deValueText: '角膜伤口',
        dsAttributeName: 'diagnose_condition',
        ifQualityControl: false,
        ifReportNode: true,
        ifRequired: false,
        ifStandard: false,
        ifTimeNode: false,
        isDel: 0,
        multiple: false,
    },
    {
        controlType: 'Input',
        coreDiseasePatId: '22021775970',
        deAttributeName: 'inner_diagnose',
        deDisable: false,
        deHide: false,
        deId: 'MCDE-00093',
        deMemo: '入院诊断',
        deTitleHide: false,
        deType: 'string',
        deValue: '角膜伤口漏',
        deValueText: '角膜伤口',
        dsAttributeName: 'diagnose_condition',
        ifQualityControl: false,
        ifReportNode: true,
        ifRequired: false,
        ifStandard: false,
        ifTimeNode: false,
        isDel: 0,
        multiple: false,
    },
    {
        controlType: 'Options',
        cvItems: [
            {
                cvCalculatedValue: 0,
                cvCode: 'MCCV-00029-001-001',
                cvDisabled: false,
                cvId: 'MCCV-00029',
                cvSelected: false,
                cvValue: '0',
                cvValueText: '无',
                fieldOrder: 1,
            },
            {
                cvCalculatedValue: 1,
                cvCode: 'MCCV-00029-001-002',
                cvDisabled: false,
                cvId: 'MCCV-00029',
                cvSelected: true,
                cvValue: '1',
                cvValueText: '肢体',
                fieldOrder: 2,
            },
            {
                cvCalculatedValue: 3,
                cvCode: 'MCCV-00029-001-003',
                cvDisabled: false,
                cvId: 'MCCV-00029',
                cvSelected: false,
                cvValue: '3',
                cvValueText: '躯干背部',
                fieldOrder: 3,
            },
            {
                cvCalculatedValue: 5,
                cvCode: 'MCCV-00029-001-004',
                cvDisabled: false,
                cvId: 'MCCV-00029',
                cvSelected: false,
                cvValue: '5',
                cvValueText: '腹部',
                fieldOrder: 4,
            },
            {
                cvCalculatedValue: 6,
                cvCode: 'MCCV-00029-001-005',
                cvDisabled: false,
                cvId: 'MCCV-00029',
                cvSelected: false,
                cvValue: '6',
                cvValueText: '头颈',
                fieldOrder: 5,
            },
        ],
        deAttributeName: 'ti_region',
        deCvId: 'MCCV-00029',
        deDisable: false,
        deHide: false,
        deId: 'MCDE-00117',
        deMemo: '损伤部位',
        deTitleHide: false,
        deType: 'int',
        dsAttributeName: 'ti_info_child',
        ifQualityControl: false,
        ifReportNode: true,
        ifRequired: false,
        ifStandard: false,
        ifTimeNode: false,
        isDel: 0,
        multiple: false,
        scoreType: 1,
        deValueText: '肢体',
    },
    {
        controlType: 'Options',
        cvItems: [
            {
                cvCalculatedValue: 0,
                cvCode: 'MCCV-00030-001-001',
                cvDisabled: false,
                cvId: 'MCCV-00030',
                cvSelected: false,
                cvValue: '0',
                cvValueText: '无',
                fieldOrder: 1,
            },
            {
                cvCalculatedValue: 1,
                cvCode: 'MCCV-00030-001-002',
                cvDisabled: false,
                cvId: 'MCCV-00030',
                cvSelected: true,
                cvValue: '1',
                cvValueText: '撕裂伤',
                fieldOrder: 2,
            },
            {
                cvCalculatedValue: 3,
                cvCode: 'MCCV-00030-001-003',
                cvDisabled: false,
                cvId: 'MCCV-00030',
                cvSelected: false,
                cvValue: '3',
                cvValueText: '钝挫伤',
                fieldOrder: 3,
            },
            {
                cvCalculatedValue: 5,
                cvCode: 'MCCV-00030-001-004',
                cvDisabled: false,
                cvId: 'MCCV-00030',
                cvSelected: false,
                cvValue: '4',
                cvValueText: '刺伤',
                fieldOrder: 4,
            },
            {
                cvCalculatedValue: 6,
                cvCode: 'MCCV-00030-001-005',
                cvDisabled: false,
                cvId: 'MCCV-00030',
                cvSelected: false,
                cvValue: '6',
                cvValueText: '弹道伤',
                fieldOrder: 5,
            },
        ],
        deAttributeName: 'ti_type',
        deCvId: 'MCCV-00030',
        deDisable: false,
        deHide: false,
        deId: 'MCDE-00118',
        deMemo: '损伤类型',
        deTitleHide: false,
        deType: 'int',
        dsAttributeName: 'ti_info_child',
        ifQualityControl: false,
        ifReportNode: true,
        ifRequired: false,
        ifStandard: false,
        ifTimeNode: false,
        isDel: 0,
        multiple: false,
        scoreType: 1,
        deValueText: '撕裂伤',
    },
    {
        controlType: 'Options',
        cvItems: [
            {
                cvCalculatedValue: 0,
                cvCode: 'MCCV-00031-001-001',
                cvDisabled: false,
                cvId: 'MCCV-00031',
                cvSelected: false,
                cvValue: '0',
                cvValueText: '无',
                fieldOrder: 1,
            },
            {
                cvCalculatedValue: 1,
                cvCode: 'MCCV-00031-001-002',
                cvDisabled: false,
                cvId: 'MCCV-00031',
                cvSelected: true,
                cvValue: '1',
                cvValueText: '有',
                fieldOrder: 2,
            },
        ],
        deAttributeName: 'ti_surface',
        deCvId: 'MCCV-00031',
        deDisable: false,
        deHide: false,
        deId: 'MCDE-00119',
        deMemo: '体表出血',
        deTitleHide: false,
        deType: 'int',
        dsAttributeName: 'ti_info_child',
        ifQualityControl: false,
        ifReportNode: true,
        ifRequired: false,
        ifStandard: false,
        ifTimeNode: false,
        isDel: 0,
        multiple: false,
        scoreType: 1,
        deValueText: '有',
    },
    {
        controlType: 'Options',
        cvItems: [
            {
                cvCode: 'MCCV-00002-001-001',
                cvDisabled: false,
                cvId: 'MCCV-00002',
                cvSelected: false,
                cvValue: '1',
                cvValueText: '交通、运输事故',
                fieldOrder: 1,
            },
            { cvCode: 'MCCV-00002-001-002', cvDisabled: false, cvId: 'MCCV-00002', cvSelected: false, cvValue: '3', cvValueText: '高处坠落', fieldOrder: 2 },
            {
                cvCode: 'MCCV-00002-001-003',
                cvDisabled: false,
                cvId: 'MCCV-00002',
                cvSelected: true,
                cvValue: '4',
                cvValueText: '暴力袭击/性侵犯',
                fieldOrder: 3,
            },
            {
                cvCode: 'MCCV-00002-001-004',
                cvDisabled: false,
                cvId: 'MCCV-00002',
                cvSelected: false,
                cvValue: '6',
                cvValueText: '动物咬伤/攻击',
                fieldOrder: 4,
            },
            {
                cvCode: 'MCCV-00002-001-005',
                cvDisabled: false,
                cvId: 'MCCV-00002',
                cvSelected: false,
                cvValue: '7',
                cvValueText: '烧伤（烫伤）/爆炸伤',
                fieldOrder: 5,
            },
            {
                cvCode: 'MCCV-00002-001-006',
                cvDisabled: false,
                cvId: 'MCCV-00002',
                cvSelected: false,
                cvValue: '8',
                cvValueText: '锐器刺伤/枪伤/贯通伤',
                fieldOrder: 6,
            },
            { cvCode: 'MCCV-00002-001-007', cvDisabled: false, cvId: 'MCCV-00002', cvSelected: false, cvValue: '9', cvValueText: '触电/雷击伤', fieldOrder: 7 },
            {
                cvCode: 'MCCV-00002-001-008',
                cvDisabled: false,
                cvId: 'MCCV-00002',
                cvSelected: false,
                cvValue: '10',
                cvValueText: '创伤（其他创伤）',
                fieldOrder: 8,
            },
            {
                cvCode: 'MCCV-00002-001-009',
                cvDisabled: false,
                cvId: 'MCCV-00002',
                cvSelected: false,
                cvValue: '35',
                cvValueText: '冬季运动损伤',
                fieldOrder: 9,
            },
            { cvCode: 'MCCV-00002-001-010', cvDisabled: false, cvId: 'MCCV-00002', cvSelected: false, cvValue: '36', cvValueText: '机械损伤', fieldOrder: 10 },
        ],
        deAttributeName: 'mpds_syndrome_id',
        deCvId: 'MCCV-00002',
        deDisable: false,
        deHide: false,
        deId: 'MCDE-00005',
        deMemo: 'MPDS症状类型',
        deTitleHide: false,
        deType: 'string',
        dsAttributeName: 'patient_info',
        ifQualityControl: false,
        ifReportNode: true,
        ifRequired: true,
        ifStandard: false,
        ifTimeNode: false,
        isDel: 0,
        multiple: true,
        separator: ',',
        deValueText: '暴力袭击/性侵犯',
    },
];
